steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/medibot-cicd/medi-bot-repo/medi-bot-app:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/medibot-cicd/medi-bot-repo/medi-bot-app:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'medi-bot-app'
    - '--image'
    - 'asia-south1-docker.pkg.dev/medibot-cicd/medi-bot-repo/medi-bot-app:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-south1'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--set-secrets'
    - 'GROQ_API_KEY=${_GROQ_API_KEY}'

images:
- 'asia-south1-docker.pkg.dev/medibot-cicd/medi-bot-repo/medi-bot-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
